# do NOT change the config version.
config_version: 1
# set locale for user dialog messages
language: de
# enable debug output
debug: false
# maximum allowed distance between both x corner values
# This is limited to 316 blocks max for performance reasons
maxScanDistanceX: 32
# maximum allowed distance between both z corner values
# This is limited to 316 blocks max for performance reasons
maxScanDistanceZ: 32